# Generated by Django 3.2.24 on 2024-02-17 04:40

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DonorReg',
            fields=[
                ('d_id', models.AutoField(primary_key=True, serialize=False)),
                ('password', models.CharField(max_length=50)),
                ('user_name', models.CharField(max_length=50)),
                ('address', models.CharField(max_length=50)),
                ('ph_no', models.CharField(max_length=50)),
            ],
            options={
                'db_table': 'donor_reg',
                'managed': False,
            },
        ),
    ]
