# Generated by Django 3.2.24 on 2024-02-17 04:40

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DonationDetails',
            fields=[
                ('donation_no', models.AutoField(primary_key=True, serialize=False)),
                ('address', models.CharField(max_length=50)),
                ('date', models.DateField()),
                ('time', models.TimeField()),
                ('status', models.CharField(max_length=50)),
            ],
            options={
                'db_table': 'donation_details',
                'managed': False,
            },
        ),
    ]
