# Generated by Django 3.2.24 on 2024-02-17 04:40

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ExcessFoodReport',
            fields=[
                ('efr_id', models.AutoField(primary_key=True, serialize=False)),
                ('food_details', models.CharField(max_length=50)),
            ],
            options={
                'db_table': 'excess_food_report',
                'managed': False,
            },
        ),
    ]
